'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Aircraft_Listing

    '''<summary>
    '''Aircraft_Criteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aircraft_Criteria As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''folderInformationUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folderInformationUpdate As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Table1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''help_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents help_text As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''search_expand_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_expand_text As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Control_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Control_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ControlImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ControlImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''controlLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents controlLink As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''StaticFolderNewSearchLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StaticFolderNewSearchLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''results_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents results_text As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''criteria_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents criteria_results As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''sort_by_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sort_by_text As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''sort_by_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sort_by_dropdown As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''sort_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sort_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''sort_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sort_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''per_page_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents per_page_text As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''per_page_dropdown_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents per_page_dropdown_ As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''per_page_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents per_page_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''per_page_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents per_page_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''view_dropdown_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view_dropdown_ As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''view_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''view_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''action_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents action_dropdown As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''actions_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actions_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''actions_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actions_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''TableCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''folders_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folders_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''folders_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folders_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''fleetAnalyzerContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fleetAnalyzerContainer As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''go_to_text_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_to_text_2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''go_to_dropdown_cell_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_to_dropdown_cell_2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''go_to_dropdown_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_to_dropdown_2 As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''go_to_submenu_dropdown_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_to_submenu_dropdown_2 As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''TableCell2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''results_text_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents results_text_ As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''paging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paging As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''previous_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previous_all As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''previous control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents previous As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''record_count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents record_count As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''next_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents next_ As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''next_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents next_all As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''splashScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents splashScreen As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''Collapse_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Collapse_Panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''close_current_folder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents close_current_folder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Table2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table2 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''mobileModelRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobileModelRow As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''mobileModelCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobileModelCell As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''MobileSearchVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileSearchVisible As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''makeModelDynamic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents makeModelDynamic As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''model_search_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents model_search_box As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''wanted_make_model_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_make_model_panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ViewTMMDropDowns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewTMMDropDowns As Global.crmWebClient.viewTypeMakeModelCtrl

    '''<summary>
    '''advanced_control_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents advanced_control_panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''advanced_image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents advanced_image As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''tableCellToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tableCellToggle As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Table4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table4 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''serText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents serText As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''ac_ser_no_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_ser_no_from As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ac_ser_no_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_ser_no_to As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''do_not_search_ac_alt_ser_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents do_not_search_ac_alt_ser_no As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''do_not_search_ac_prev_reg_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents do_not_search_ac_prev_reg_no As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ac_reg_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_reg_no As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ac_reg_no_exact_match control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_reg_no_exact_match As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''mobileSearchRadioToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobileSearchRadioToggle As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''mobileStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobileStatus As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''Aircraft_Search_Box_toggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aircraft_Search_Box_toggle As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''comp_folder_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_folder_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''static_folder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents static_folder As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''static_folder_ac_ids control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents static_folder_ac_ids As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''transaction_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents transaction_box As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''transaction_retail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents transaction_retail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''retail_transaction_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents retail_transaction_label As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''journ_subcat_code_part1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_subcat_code_part1 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''journ_subcat_code_part2_operator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_subcat_code_part2_operator As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''journ_subcat_code_part2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_subcat_code_part2 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''journ_subcat_code_part3_operator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_subcat_code_part3_operator As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''journ_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_id As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''journ_newac_flag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_newac_flag As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''jcat_used_retail_sales_flag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jcat_used_retail_sales_flag As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''mecbe1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mecbe1 As Global.AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender

    '''<summary>
    '''mecbe2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mecbe2 As Global.AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender

    '''<summary>
    '''journ_exclude_internal_transactions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_exclude_internal_transactions As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''journ_subcat_code_part3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_subcat_code_part3 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''journ_date_operator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_date_operator As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''journ_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents journ_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''VALIDATE_TransactionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VALIDATE_TransactionDate As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''TableCell3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell3 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''acHistSearchUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acHistSearchUpdate As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''searchTransaction_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchTransaction_button As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''transaction_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents transaction_search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''market_search_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents market_search_box As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''aerodex_toggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aerodex_toggle As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''market control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents market As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ac_lifecycle_stage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_lifecycle_stage As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ac_ownership_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_ownership_type As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ac_previously_owned_flag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_previously_owned_flag As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lease_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lease_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''acSearchUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acSearchUpdate As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''acSearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acSearchButton As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''acsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acsearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''aircraftShowTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraftShowTable As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''aircraftShowNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraftShowNotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''placerHold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents placerHold As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''aircraftNotesDateToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraftNotesDateToggle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CompareValidator4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator4 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''notesDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notesDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CalendarExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender3 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''cal_image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cal_image As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''event_search_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_search_box As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''eventCategoryTypeDropdowns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eventCategoryTypeDropdowns As Global.crmWebClient.eventCategoryType

    '''<summary>
    '''Table12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table12 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''events_months control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents events_months As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''event_days control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_days As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''event_hours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_hours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''event_minutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_minutes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''clearTimesMarket control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearTimesMarket As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''event_type_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_type_text As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EventSearchUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventSearchUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''eventsSearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eventsSearchButton As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''events_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents events_search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''eventAlertMaintenanceButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eventAlertMaintenanceButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CompareValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator3 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''Validate_EventMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Validate_EventMonths As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CompareValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator2 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''Validate_EventDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Validate_EventDays As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''requiredDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requiredDays As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RequiredFieldValidator3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator3 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CompareValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator1 As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''Validate_EventHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Validate_EventHours As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''RequiredFieldValidator2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Validate_EventMinutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Validate_EventMinutes As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''ac_advanced_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_advanced_update As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ac_advanced_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_advanced_search As Global.AjaxControlToolkit.TabContainer

    '''<summary>
    '''location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents location As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''viewCCSTDropDownsAirport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCCSTDropDownsAirport As Global.crmWebClient.continentRegionDropdownsCtrl

    '''<summary>
    '''location_dynamic_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents location_dynamic_panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''equip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents equip As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''COMPARE_us_ac_maintained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_us_ac_maintained As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''us_ac_maintained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents us_ac_maintained As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_foreign_ac_maintained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_foreign_ac_maintained As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''foreign_ac_maintained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents foreign_ac_maintained As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_emp_provider_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_emp_provider_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''emp_provider_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emp_provider_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_emp_program_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_emp_program_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''emp_program_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emp_program_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_emgp_provider_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_emgp_provider_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''emgp_provider_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emgp_provider_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_emgp_program_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_emgp_program_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''emgp_program_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emgp_program_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_amp_provider_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_amp_provider_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''amp_provider_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amp_provider_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_amp_program_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_amp_program_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''amp_program_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amp_program_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_amtp_provider_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_amtp_provider_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''amtp_provider_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amtp_provider_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''COMPARE_amtp_program_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_amtp_program_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''amtp_program_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amtp_program_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''maintenance_item control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenance_item As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''acmaint_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acmaint_date As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''acmaint_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acmaint_time As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''COMPARE_acmaint_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_acmaint_value As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''acmaint_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acmaint_value As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''acmaint_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acmaint_chk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''maintenance_item1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenance_item1 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''acmaint_date1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acmaint_date1 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''acmaint_time1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acmaint_time1 As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''COMPARE_acmaint_value1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_acmaint_value1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''acmaint_value1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acmaint_value1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''acmaint_chk1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acmaint_chk1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''equip_dynamic_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents equip_dynamic_panel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''company_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_contact As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''Table3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table3 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''comp_alt_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_alt_name As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''COMPARE_comp_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_comp_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comp_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''COMPARE_comp_agency_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_comp_agency_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comp_agency_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_agency_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comp_not_in_selected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_not_in_selected As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cref_contact_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cref_contact_type As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''COMPARE_contact_first_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_contact_first_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''contact_first_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contact_first_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''COMPARE_contact_last_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_contact_last_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''contact_last_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contact_last_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''COMPARE_comp_email_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_comp_email_address As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comp_email_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_email_address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''COMPARE_contact_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_contact_title As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''contact_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contact_title As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''COMPARE_comp_phone_office control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_comp_phone_office As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comp_phone_office control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_phone_office As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''COMPARE_comp_address1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_comp_address1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comp_address1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_address1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cref_business_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cref_business_type As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''COMPARE_comp_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_comp_city As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comp_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_city As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''COMPARE_comp_zip_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_comp_zip_code As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''comp_zip_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comp_zip_code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''COMPARE_cref_comp_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_cref_comp_id As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cref_comp_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cref_comp_id As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''viewCCSTDropDowns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCCSTDropDowns As Global.crmWebClient.continentRegionDropdownsCtrl

    '''<summary>
    '''COMPARE_cref_owner_percent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents COMPARE_cref_owner_percent As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cref_owner_percent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cref_owner_percent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbFractionalProgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFractionalProgram As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''AttrTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttrTab As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''TestLoadAttributes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestLoadAttributes As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''attrBoolRan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attrBoolRan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AttributesPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttributesPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Custom_MPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Custom_MPM As Global.AjaxControlToolkit.TabPanel

    '''<summary>
    '''advanced_search_categories_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents advanced_search_categories_table As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''infoButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents infoButton1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''custom_pref_name1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''custom_pref_name10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_name10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''custom_pref_text10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_pref_text10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''listingUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listingUpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''aircraft_attention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraft_attention As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FolderInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FolderInformation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mobileDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobileDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''ResultsSearchData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultsSearchData As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''AircraftSearchDataGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AircraftSearchDataGrid As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''TransactionSearchDataGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSearchDataGrid As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''EventsDataGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventsDataGrid As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''TransactionSearchDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSearchDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''AircraftSearchDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AircraftSearchDataList As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''page_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents page_type As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Aircraft_Bottom_Paging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aircraft_Bottom_Paging As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''go_to_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_to_text As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''go_to_dropdown_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_to_dropdown_ As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''go_to_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_to_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''go_to_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_to_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList

    '''<summary>
    '''bottom_paging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottom_paging As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bottom_previous_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottom_previous_all As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''bottom_previous control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottom_previous As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''bottom_record_count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottom_record_count As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bottom_next_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottom_next_ As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''bottom_next_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bottom_next_all As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As crmWebClient.EvoTheme
        Get
            Return CType(MyBase.Master, crmWebClient.EvoTheme)
        End Get
    End Property
End Class
