'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Airport_Listing
    
    '''<summary>
    '''Table3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table3 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''expand_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents expand_text As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''controlLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents controlLink As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''results_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents results_text As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''criteriaUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents criteriaUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''criteria_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents criteria_results As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Collapse_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Collapse_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Table4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table4 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''airportSearchTxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airportSearchTxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''airportSearchID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airportSearchID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''airportCitytxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airportCitytxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''airportIATACodetxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airportIATACodetxt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''SearchUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchUpdate As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''airportSearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airportSearchButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''listingUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents listingUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ResultsSearchDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultsSearchDataList As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''ap_attention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ap_attention As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''mobileUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobileUpdate As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''airportName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airportName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''ac_attention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_attention As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''mobileDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mobileDataList As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''divTabLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divTabLoading As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
