'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class _details

  '''<summary>
  '''white_background_style control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents white_background_style As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''css_card_left control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents css_card_left As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''companyCard control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents companyCard As Global.crmWebClient._companyCard

  '''<summary>
  '''aircraftCard control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents aircraftCard As Global.crmWebClient.aircraftCard

  '''<summary>
  '''css_card_right control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents css_card_right As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''contactCard control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contactCard As Global.crmWebClient._contactCard

  '''<summary>
  '''Company_Tabs1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Company_Tabs1 As Global.crmWebClient.Company_Tabs

  '''<summary>
  '''Aircraft_Tabs1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Aircraft_Tabs1 As Global.crmWebClient.Aircraft_Tabs

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As crmWebClient.main_site
    Get
      Return CType(MyBase.Master, crmWebClient.main_site)
    End Get
  End Property
End Class
