'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DisplayModelDetail
    
    '''<summary>
    '''splashScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents splashScreen As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''model_display_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents model_display_panel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''browseTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents browseTable As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''know_more control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents know_more As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''model_name_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents model_name_admin As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''model_id_admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents model_id_admin As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''information control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents information As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''information_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents information_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''information_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents information_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''internalNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents internalNotes As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''internalNotes_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents internalNotes_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''internalNotes_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents internalNotes_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''engine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents engine As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''engine_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents engine_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''engine_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents engine_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''maintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenance As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''maintenance_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenance_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''maintenance_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenance_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''picture_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents picture_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''operational control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operational As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''operational_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operational_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''operational_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operational_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''utilization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilization As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''utilization_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilization_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''utilization_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilization_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''features control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''features_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''features_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''topics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topics As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''topics_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topics_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''topics_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents topics_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''basic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents basic As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''basic_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents basic_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''basic_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents basic_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''costs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents costs As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''costs_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents costs_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''costs_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents costs_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''resources control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resources As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''resources_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resources_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''resources_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resources_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''sale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sale As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''sale_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sale_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''sale_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sale_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''assett_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents assett_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''assett_label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents assett_label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dealer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dealer As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''dealer_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dealer_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''dealer_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dealer_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''userInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userInterest As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''userInterest_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userInterest_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''userInterest_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userInterest_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''maintenanceDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenanceDetails As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''maintenanceDetails_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenanceDetails_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''maintenanceDetails_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenanceDetails_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''no_model_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents no_model_text As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As crmWebClient.EmptyEvoTheme
        Get
            Return CType(MyBase.Master,crmWebClient.EmptyEvoTheme)
        End Get
    End Property
End Class
