'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class evoProjectConversion

  '''<summary>
  '''count_line control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents count_line As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''click_line control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents click_line As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''run_ac_export control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents run_ac_export As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''run_event_export control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents run_event_export As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''run_market_summary_export control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents run_market_summary_export As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''results_label control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents results_label As Global.System.Web.UI.WebControls.Label
End Class
