'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8794
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class export_creator

  '''<summary>
  '''Head1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

  '''<summary>
  '''form1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''file_menu control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_menu As Global.System.Web.UI.WebControls.Menu

  '''<summary>
  '''no_export_error control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents no_export_error As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''company_new control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents company_new As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''export_title control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents export_title As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''attention control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents attention As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''type_of_info control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents type_of_info As Global.System.Web.UI.WebControls.CheckBoxList

  '''<summary>
  '''phone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phone As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''contact_phone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contact_phone As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''custom_export control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents custom_export As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''export_label control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents export_label As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''export_now control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents export_now As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''load_export_label control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents load_export_label As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''load_export control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents load_export As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''create_export_template control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents create_export_template As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''cancel_now control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cancel_now As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''merge_lists control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents merge_lists As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''export_info_box control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents export_info_box As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''open_project control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents open_project As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''open_project_ddl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents open_project_ddl As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''Open_Project_Btn control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Open_Project_Btn As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''file_open_dialog control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_open_dialog As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''selected_export_template control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents selected_export_template As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''file_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_name As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''file_description control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_description As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''file_shared control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_shared As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''file_id control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_id As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''check_market_default control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents check_market_default As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''model_list control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents model_list As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''model_list_source control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents model_list_source As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''default_label control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents default_label As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''default_model_export control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents default_model_export As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''warning_label control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents warning_label As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''file_save control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_save As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''file_save_as control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_save_as As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''cancel_file_save control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cancel_file_save As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''file_delete control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents file_delete As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''export_type_drop control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents export_type_drop As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''choice_to_export control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents choice_to_export As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''Button1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Button2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Button3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Button3 As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Button4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Button4 As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''info_to_export control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents info_to_export As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''Button5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Button5 As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Button6 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Button6 As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''gridview1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents gridview1 As Global.System.Web.UI.WebControls.DataGrid

  '''<summary>
  '''ac_prospect control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ac_prospect As Global.System.Web.UI.WebControls.TextBox
End Class
