'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class fullTextSearch
    
    '''<summary>
    '''splashScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents splashScreen As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''full_text_search_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents full_text_search_update As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''buttonsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonsTable As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''TableCell00 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell00 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''close_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents close_button As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''debug_output control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents debug_output As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''full_text_search_input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents full_text_search_input As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''full_text_search_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents full_text_search_button As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''full_text_search_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents full_text_search_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''full_text_search_no_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents full_text_search_no_results As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''full_text_search_results_row control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents full_text_search_results_row As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''modelColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modelColumn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''modelTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modelTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''aircraftColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraftColumn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''aircraftTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraftTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''companyColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents companyColumn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''companyTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents companyTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''contactColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contactColumn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''contactTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contactTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yachtColumn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yachtColumn As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''yachtTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yachtTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As crmWebClient.EmptyEvoTheme
        Get
            Return CType(MyBase.Master,crmWebClient.EmptyEvoTheme)
        End Get
    End Property
End Class
