'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8745
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class homebaseOpCosts

  '''<summary>
  '''splashScreen control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents splashScreen As Global.System.Web.UI.UpdateProgress

  '''<summary>
  '''opCosts_panel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents opCosts_panel As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''container_opCosts_listing control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents container_opCosts_listing As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''opCosts_listing_text control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents opCosts_listing_text As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As crmWebClient.EmptyHomebaseTheme
    Get
      Return CType(MyBase.Master, crmWebClient.EmptyHomebaseTheme)
    End Get
  End Property
End Class
