'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class home_tile
    
    '''<summary>
    '''evo_scripts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents evo_scripts As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''splashScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents splashScreen As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''crmPanelVisibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crmPanelVisibility As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''UpdateProgress3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress3 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''crm_update_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_update_panel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''crm_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_tab As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''crm_action_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_action_panel As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''today_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents today_date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''demo_attention_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents demo_attention_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''calendar_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calendar_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''timeframepanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents timeframepanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''crm_calendar_timeframe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_calendar_timeframe As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''crm_calendar_timeframe_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_calendar_timeframe_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''main_calendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main_calendar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''main_calendar_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main_calendar_txt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''crm_market_overview_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_market_overview_panel As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''crm_market_overview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_market_overview As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''toggleSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents toggleSales As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''crm_event_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_event_panel As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''crm_event_update_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_event_update_panel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''crm_time_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_time_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''crm_event_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_event_time As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''crm_event_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_event_category As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''crm_event_listing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_event_listing As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''crm_wanteds_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_wanteds_panel As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''crm_wanted_update_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_wanted_update_panel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''crm_wanted_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_wanted_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''crm_user_activity_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_user_activity_panel As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''user_activity_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents user_activity_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''crm_client_db_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents crm_client_db_panel As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''client_database_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents client_database_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''home_right_visible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents home_right_visible As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''home_companies_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents home_companies_txt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''home_contacts_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents home_contacts_txt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''home_aircraft_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents home_aircraft_txt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''home_notes_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents home_notes_txt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''home_documents_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents home_documents_txt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''evo_display_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents evo_display_table As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''main_home_update_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents main_home_update_panel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''makeModelButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents makeModelButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''dashboardSaveButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dashboardSaveButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''queryOutput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents queryOutput As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''gridItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridItems As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''BoxContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoxContainer As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''modelSelectContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modelSelectContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''makeModelDynamic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents makeModelDynamic As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''boxCustomizerContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents boxCustomizerContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''dashboardDynamic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dashboardDynamic As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''FleetSummaryContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FleetSummaryContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''FleetSummaryContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FleetSummaryContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''FleetSummaryHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FleetSummaryHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fleet_summary_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fleet_summary_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MarketOverviewContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarketOverviewContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MarketOverviewContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarketOverviewContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''MarketOverviewHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarketOverviewHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''market_overview_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents market_overview_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Events_Container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Events_Container As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''events_container_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents events_container_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''eventsHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eventsHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''event_time_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_time_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''event_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_time As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''event_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_category As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''event_listing_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_listing_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''WantedContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WantedContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''WantedContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WantedContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''wanted_listing_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_listing_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CompanyAnalyticsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyAnalyticsContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CompanyAnalyticsContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyAnalyticsContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''companyAnalyticsHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents companyAnalyticsHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''company_analytics_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_analytics_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''AircraftAnalyticsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AircraftAnalyticsContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''aircraft_analytics_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraft_analytics_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Cumulative_New_Deliveries_Container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cumulative_New_Deliveries_Container As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Cumulative_New_Deliveries_Container_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cumulative_New_Deliveries_Container_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''cumulative_deliveries_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cumulative_deliveries_header As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cumulative_deliveries_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cumulative_deliveries_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ActionItemsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionItemsContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ActionItemsContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActionItemsContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''actionItemsHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents actionItemsHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''evo_action_items control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents evo_action_items As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ReportsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportsContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ReportsContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportsContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''reportHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reportHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''custom_reports_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_reports_results As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''custom_reports_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents custom_reports_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MyAirportsContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyAirportsContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MyAirportsContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MyAirportsContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''myAirportHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myAirportHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''months_choice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents months_choice As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''my_airports_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents my_airports_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''modifyListAirport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modifyListAirport As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''div_airports_label_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_airports_label_table As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''airportsResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airportsResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''airportsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airportsTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''mympm_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mympm_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SearchContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SearchContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''searchBoxVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchBoxVisible As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''HomeSearchBoxText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeSearchBoxText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''folder_events_tab_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folder_events_tab_text As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RecentItemsContainers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecentItemsContainers As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''RecentItemsContainers_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RecentItemsContainers_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''recentActivityHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recentActivityHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''recent_aircraft_activity_evo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recent_aircraft_activity_evo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FolderContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FolderContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''FolderContainer_delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FolderContainer_delete As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''folderHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folderHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''show_hidden_folders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents show_hidden_folders As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''hide_shared control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hide_shared As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''aircraft_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraft_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''aircraft_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraft_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''history_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''history_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''company_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''company_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''contact_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contact_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''contact_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contact_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''event_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''event_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''wanted_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''wanted_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''performance_specs_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents performance_specs_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''performance_specs_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents performance_specs_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''operating_costs_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operating_costs_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''operating_costs_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operating_costs_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''marketing_summary_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents marketing_summary_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''marketing_summary_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents marketing_summary_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''airport_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airport_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''airport_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airport_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''values_folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents values_folder_container As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''values_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents values_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''no_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents no_projects As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yacht_display_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_display_table As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''yacht_update_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_update_panel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''yacht_summary_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_summary_tab As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''TabPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''yacht_summary_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_summary_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yacht_quick_search_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_quick_search_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''yacht_search_control_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_search_control_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''___yt_model_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___yt_model_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''YachtModelDynamic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents YachtModelDynamic As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''___yacht_name_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___yacht_name_search As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''___ypn_previous_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___ypn_previous_name As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''___hull_MFR_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___hull_MFR_from As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''___yt_call_sign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___yt_call_sign As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''___for_sale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___for_sale As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''___for_lease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___for_lease As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''___for_charter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___for_charter As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''___yt_market control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___yt_market As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''___yt_year_mfr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___yt_year_mfr As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''___yt_year_dlv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___yt_year_dlv As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''___operator_length control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___operator_length As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''___length_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___length_to As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''___us_standard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___us_standard As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''___metric_standard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___metric_standard As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''mecbe1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mecbe1 As Global.AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender
    
    '''<summary>
    '''mecbe2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mecbe2 As Global.AjaxControlToolkit.MutuallyExclusiveCheckBoxExtender
    
    '''<summary>
    '''___yt_motor_sailing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ___yt_motor_sailing As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''company_name___ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_name___ As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''company_contact_first___ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_contact_first___ As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''company_contact_last___ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_contact_last___ As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''company_email_address___ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_email_address___ As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''company_relationship___ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents company_relationship___ As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''searchYacht control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchYacht As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''searchYachtCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchYachtCompany As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''TabPanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanel3 As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''yacht_latest_news_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_latest_news_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yacht_index_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_index_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''yacht_index_wait_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_index_wait_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''yacht_index_tab_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_index_tab_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yachtIndexPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yachtIndexPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''yacht_action_items control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_action_items As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''yacht_action_items_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_action_items_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yacht_small_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_small_tab As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''TabPanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanel6 As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''recent_aircraft_activity_yacht control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recent_aircraft_activity_yacht As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''yacht_company_recent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_company_recent As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''yacht_contact_recent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_contact_recent As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''yacht_recent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_recent As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''TabPanel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabPanel7 As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''yacht_folder_update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_folder_update As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''yacht_hidden_folders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_hidden_folders As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Panel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''yacht_company_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_company_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''Panel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''yacht_contact_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_contact_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''Panel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel7 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''yacht_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''yacht_history_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_history_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''Panel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''yacht_event_projects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents yacht_event_projects As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents time As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As crmWebClient.main_site
        Get
            Return CType(MyBase.Master,crmWebClient.main_site)
        End Get
    End Property
End Class
