'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class searchSummary
    
    '''<summary>
    '''splashScreen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents splashScreen As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''browseTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents browseTable As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''table_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents table_container As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''leftTabContainerCell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents leftTabContainerCell As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''folder_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folder_container As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''folder_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folder_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''general_tree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents general_tree As Global.System.Web.UI.WebControls.TreeView
    
    '''<summary>
    '''holder_for_new_tree_views control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents holder_for_new_tree_views As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''holder_for_new_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents holder_for_new_table As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''summary_container control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents summary_container As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''summary_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents summary_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''summary_table_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents summary_table_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''second_summary_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents second_summary_tab As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''second_summary_table_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents second_summary_table_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As crmWebClient.EmptyEvoTheme
        Get
            Return CType(MyBase.Master,crmWebClient.EmptyEvoTheme)
        End Get
    End Property
End Class
