'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5472
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class spec_sheet_aspx

  '''<summary>
  '''assHead control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents assHead As Global.System.Web.UI.HtmlControls.HtmlHead

  '''<summary>
  '''assBodyID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents assBodyID As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''assIDForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents assIDForm As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''outerDivasIDForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents outerDivasIDForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''makemodelname control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents makemodelname As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''SP control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents SP As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''TP control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TP As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''PP control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents PP As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''BR control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents BR As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''EB control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents EB As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''addAsking control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents addAsking As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''WD control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents WD As Global.System.Web.UI.WebControls.RadioButtonList

  '''<summary>
  '''HelpText control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents HelpText As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''btnRunReport control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnRunReport As Global.System.Web.UI.WebControls.Button
End Class
