'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class staticFolderEditor
    
    '''<summary>
    '''pnl_static_folder_editor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_static_folder_editor As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''outerDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents outerDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''close_button_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents close_button_new As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''debug_output control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents debug_output As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''tabContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabContainer As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''tabPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabPanel1 As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lbl_static_folder_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_static_folder_name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnl_static_folder_editor_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_static_folder_editor_results As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''selected_folder_rows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selected_folder_rows As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''remove_folder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents remove_folder As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''reset_page control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reset_page As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''save_folder_edits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents save_folder_edits As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div_static_folder_editor_results_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_static_folder_editor_results_table As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''folderResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folderResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''folderTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folderTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tabPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabPanel2 As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''lbl_quick_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_quick_search As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''quickSearchPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quickSearchPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''quick_search_input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quick_search_input As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''continent_or_region control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents continent_or_region As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''quick_search_location_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quick_search_location_box As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''quick_search_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents quick_search_button As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''searchCodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchCodes As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''search_reg_nos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_reg_nos As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''pnl_quick_search_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_quick_search_results As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''selected_quick_search_rows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selected_quick_search_rows As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''folderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folderName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''save_quick_search_results_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents save_quick_search_results_button As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''div_quick_search_results_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_quick_search_results_table As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''searchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchResults As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''searchTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchTable As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As crmWebClient.EmptyEvoTheme
        Get
            Return CType(MyBase.Master,crmWebClient.EmptyEvoTheme)
        End Get
    End Property
End Class
