'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class viewtopdf_aspx
    
    '''<summary>
    '''mapText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mapText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''contentClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contentClass As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''outerDivViewToPDFID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents outerDivViewToPDFID As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''form_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form_title As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''view_type_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents view_type_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''attentionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attentionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MR_Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''MR_DESC_SPECS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_DESC_SPECS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_OPERATING_COSTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_OPERATING_COSTS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_BPS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_BPS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_BOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_BOC As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_FMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_FMS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_UP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_UP As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_Fleet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_Fleet As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_LOCATIONS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_LOCATIONS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_UTILIZATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_UTILIZATION As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C_MPAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_MPAS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''S_SM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S_SM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MCOMP_FMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MCOMP_FMS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_STAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_STAT As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_OP_COSTS_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_OP_COSTS_2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''L_TM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_TM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C_MOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_MOD As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''O_MOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents O_MOD As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''indent_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents indent_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MMS_CHARTS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_CHARTS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''L_TL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_TL As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C_OP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_OP As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''O_OS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents O_OS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''O_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents O_ENG As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MC_FSBM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MC_FSBM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''F_DSPM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F_DSPM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MC_AVG_DOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MC_AVG_DOM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CRM_Wanteds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CRM_Wanteds As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_AA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_AA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''rangeTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rangeTab As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''MMS_RM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_RM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''first_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents first_model As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''second_model control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents second_model As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''destination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents destination As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''destination_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents destination_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''current_market_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents current_market_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''MR_CMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_CMS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_CMACFORSALE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_CMACFORSALE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_MARKET_CHARACTERISTICS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_MARKET_CHARACTERISTICS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_DOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_DOM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_RECENT_MARKET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_RECENT_MARKET As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_FSS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_FSS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''L_AL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_AL As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C_AC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_AC As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_BAFS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_BAFS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''O_AC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents O_AC As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MC_AVG_PRICE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MC_AVG_PRICE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''PAD_DET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PAD_DET As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''F_DM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F_DM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_BRMA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_BRMA As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''F_DFS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F_DFS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''F_NVU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F_NVU As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''S_3D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S_3D As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''sales_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sales_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''MR_SITRENS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_SITRENS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_RRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_RRS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''indent_label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents indent_label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MMS_Sale_Prices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_Sale_Prices As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_UPGRADE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_UPGRADE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_STBM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_STBM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_STBMFR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_STBMFR As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_STBAFTT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_STBAFTT As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_STBWC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_STBWC As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''L_MRT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_MRT As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MMS_BRRS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MMS_BRRS As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MR_SALE_PRICES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MR_SALE_PRICES As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''S_FQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S_FQ As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Lease_View_PDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lease_View_PDF As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C_AF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_AF As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Operator_View_PDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Operator_View_PDF As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C_LOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_LOC As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''C_LOCITY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents C_LOCITY As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''O_COUNTRY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents O_COUNTRY As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''F_DTD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F_DTD As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''MC_SOLD_PM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MC_SOLD_PM As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''L_LE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_LE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''L_LDTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents L_LDTE As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''F_LTG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents F_LTG As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''utilizationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilizationSummary As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''utilizationRoutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilizationRoutes As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''utilizationModels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilizationModels As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''utilizationOperators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilizationOperators As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''utilizationAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilizationAC As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''refuel_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents refuel_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''utilizationInternational control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilizationInternational As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''utilizationGraphs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilizationGraphs As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''utilization_state_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents utilization_state_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''valuation_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valuation_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''current_market_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents current_market_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''mfr_year_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mfr_year_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''by_month_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents by_month_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''residual_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents residual_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''aftt_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aftt_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CP As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''prepared_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prepared_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''check_prepared_for control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents check_prepared_for As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''prepared_for control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents prepared_for As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chk_header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_header As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chk_alt_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_alt_name As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''logo_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logo_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''S_COL_LABEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S_COL_LABEL As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''S_COL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents S_COL As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''market_color control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents market_color As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''month_timeframe_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents month_timeframe_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''month_timeframe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents month_timeframe As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''No_Background control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents No_Background As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''no_back_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents no_back_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''fuel_burn_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuel_burn_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''fuel_burn_liters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuel_burn_liters As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''WD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WD As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''HelpText2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HelpText2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ac_checkbox_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_checkbox_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''acpic_cover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acpic_cover As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''achigh_check control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents achigh_check As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''useStandardOrMetric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents useStandardOrMetric As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''mpm_attention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpm_attention As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''attentionAirport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents attentionAirport As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''extra_map_warning_label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents extra_map_warning_label As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''resetButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resetButton As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRunReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRunReport As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''select_all_types_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents select_all_types_button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''updateSelections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateSelections As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''btnSave_Selections control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave_Selections As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''AVG_SOLD_PER_MONTH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AVG_SOLD_PER_MONTH As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''AVG_PRICE_MONTH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AVG_PRICE_MONTH As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''FOR_SALE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FOR_SALE As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''PER_MONTH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PER_MONTH As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''OP_COUNTRY_CHART control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OP_COUNTRY_CHART As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''AVG_DAYS_ON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AVG_DAYS_ON As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''SPI_QUARTER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPI_QUARTER As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''M_TREND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_TREND As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''M_TREND2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents M_TREND2 As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''SALES_TRENDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SALES_TRENDS As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''LEASES_SOLD_PER_MONTH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LEASES_SOLD_PER_MONTH As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''DOCS_BY_MONTH_GRAPH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DOCS_BY_MONTH_GRAPH As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''VALUES_CHART control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VALUES_CHART As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''VALUES_CHART2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VALUES_CHART2 As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''VALUES_CHART3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VALUES_CHART3 As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''IN_OPERATION_CHART control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IN_OPERATION_CHART As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''searchPanelToggle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchPanelToggle As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''modelUpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modelUpdatePanel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''acIDText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acIDText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''variantThere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents variantThere As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''modelList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modelList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''year_start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents year_start As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''year_end control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents year_end As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''aftt_start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aftt_start As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''aftt_end control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aftt_end As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''aircraft_registration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aircraft_registration As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''loadWhatUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loadWhatUpdate As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''loadWhatAC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loadWhatAC As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''variantModelText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents variantModelText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FolderInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FolderInformation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''StaticFolderNewSearchLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StaticFolderNewSearchLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''acRangeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acRangeText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ac_market control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ac_market As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''start_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents start_date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''end_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents end_date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''VariantList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VariantList As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''modelAirframeTypeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modelAirframeTypeCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ModelTypeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModelTypeCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ModelWeightClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModelWeightClass As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''invisible_label_parent_image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents invisible_label_parent_image As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''large_graph_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents large_graph_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''graph_update_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents graph_update_panel As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''tabcontainer_graph control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabcontainer_graph As Global.AjaxControlToolkit.TabContainer
    
    '''<summary>
    '''graph_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents graph_panel As Global.AjaxControlToolkit.TabPanel
    
    '''<summary>
    '''featuresGaugePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents featuresGaugePanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''features1text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features1text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''features1image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features1image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''features2text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features2text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''features2image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features2image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''features3text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features3text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''features3image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features3image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''features4text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features4text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''features4image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features4image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''features5text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features5text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''features5image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features5image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''features6text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features6text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''features6image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents features6image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''program1text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents program1text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''program1image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents program1image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''program2text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents program2text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''program2image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents program2image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''program3text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents program3text As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''program3image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents program3image As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png20 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''visualizationGraphText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visualizationGraphText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''visualizationPNG1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents visualizationPNG1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png11 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png12 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png13 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png14 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png15 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png16 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText17 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png17 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText18 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png18 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText19 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png19 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphTextGuage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphTextGuage1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngGuage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngGuage1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphTextGuageUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphTextGuageUS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngGuageUS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngGuageUS As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphTextGuageForeign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphTextGuageForeign As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngGuageForeign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngGuageForeign As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphTextGuage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphTextGuage2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngGuage2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngGuage2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphTextGauge3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphTextGauge3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngGauge3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngGauge3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphTextGauge4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphTextGauge4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngGauge4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngGauge4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphTextGauge5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphTextGauge5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngGauge5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngGauge5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText21 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png21 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ValueGraphText22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValueGraphText22 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png22 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ValueGraphText23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValueGraphText23 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png23 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText24 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png24 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphTextGauge6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphTextGauge6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngGauge6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngGauge6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText25 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png25 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText26 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png26 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText32 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png32 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valueGraphText33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valueGraphText33 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''png33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents png33 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valuuationGraph1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valuuationGraph1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngValuation1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngValuation1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valuuationGraph2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valuuationGraph2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngValuation2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngValuation2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valuuationGraph3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valuuationGraph3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngValuation3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngValuation3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valuuationGraph4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valuuationGraph4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngValuation4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngValuation4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''valuuationGraph5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valuuationGraph5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pngValuation5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pngValuation5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''invisible_count_years control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents invisible_count_years As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As crmWebClient.EmptyEvoTheme
        Get
            Return CType(MyBase.Master,crmWebClient.EmptyEvoTheme)
        End Get
    End Property
End Class
