'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Wanted_Listing
    
    '''<summary>
    '''Wanted_Criteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Wanted_Criteria As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Table13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table13 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''wanted_help_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_help_text As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_search_expand_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_search_expand_text As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_Control_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_Control_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''wanted_ControlImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_ControlImage As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''wanted_results_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_results_text As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_criteria_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_criteria_results As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''wanted_sort_by_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_sort_by_text As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_sort_by_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_sort_by_dropdown As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_sort_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_sort_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_sort_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_sort_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_per_page_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_per_page_text As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_per_page_dropdown_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_per_page_dropdown_ As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_per_page_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_per_page_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_per_page_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_per_page_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_go_to_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_go_to_text As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_go_to_dropdown_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_go_to_dropdown_ As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_go_to_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_go_to_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_go_to_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_go_to_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_action_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_action_dropdown As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_actions_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_actions_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_actions_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_actions_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''TableCell1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_folders_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_folders_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_folders_submenu_dropdown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_folders_submenu_dropdown As Global.System.Web.UI.WebControls.BulletedList
    
    '''<summary>
    '''wanted_results_text_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_results_text_ As Global.System.Web.UI.WebControls.TableCell
    
    '''<summary>
    '''wanted_paging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_paging As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''wanted_previous_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_previous_all As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''wanted_previous control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_previous As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''wanted_record_count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_record_count As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''wanted_next_ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_next_ As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''wanted_next_all control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_next_all As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''wanted_PanelCollapseEx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_PanelCollapseEx As Global.AjaxControlToolkit.CollapsiblePanelExtender
    
    '''<summary>
    '''wanted_Collapse_Panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_Collapse_Panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''close_current_folder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents close_current_folder As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Table4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table4 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''wanted_model_search_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_model_search_box As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''wanted_make_model_panel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_make_model_panel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ViewTMMDropDowns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ViewTMMDropDowns As Global.crmWebClient.viewTypeMakeModelCtrl
    
    '''<summary>
    '''Table16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table16 As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''wanted_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_from As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''wanted_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_to As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''wanted_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_search As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''reset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ValidateWantedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidateWantedFrom As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''ValidateWantedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidateWantedTo As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''wanted_interested control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_interested As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''wanted_folder_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_folder_name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''amwant_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents amwant_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''wanted_placed_by control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_placed_by As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''FolderInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FolderInformation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''wanted_attention control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wanted_attention As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Results As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As crmWebClient.EvoTheme
        Get
            Return CType(MyBase.Master,crmWebClient.EvoTheme)
        End Get
    End Property
End Class
