'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class globalRss

  '''<summary>
  '''news_header control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents news_header As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As crmWebClient.ABI
    Get
      Return CType(MyBase.Master, crmWebClient.ABI)
    End Get
  End Property
End Class
