'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8933
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class abiContact

  '''<summary>
  '''ValidationSummary1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

  '''<summary>
  '''news_header control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents news_header As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''attention control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents attention As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''dealerInformation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dealerInformation As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''modelInformation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents modelInformation As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''companyID control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents companyID As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''textBody control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents textBody As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''interest control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents interest As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''company_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents company_name As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''required_first_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents required_first_name As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''first_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents first_name As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''required_last_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents required_last_name As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''last_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents last_name As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''address control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents address As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''address_cont control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents address_cont As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''city control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents city As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''state control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents state As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''zip control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents zip As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''country control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents country As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''phone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents phone As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''required_email control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents required_email As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''email control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents email As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''message control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents message As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''RecaptchaFail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents RecaptchaFail As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''submitForm control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents submitForm As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As crmWebClient.ABI
    Get
      Return CType(MyBase.Master, crmWebClient.ABI)
    End Get
  End Property
End Class
