'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8933
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class abiForsale

  '''<summary>
  '''aside_right control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents aside_right As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''leftHeaderText control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents leftHeaderText As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''leftCategory control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents leftCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''dealersRepeater control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dealersRepeater As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''companyInformation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents companyInformation As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''component control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents component As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''ac_header control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ac_header As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''acIncludedText control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents acIncludedText As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''acListLiteral control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents acListLiteral As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''acDetailedList control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents acDetailedList As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''companyWantedLiteral control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents companyWantedLiteral As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''moreModelInformationLiteral control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents moreModelInformationLiteral As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''viewAllDiv control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents viewAllDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''newsByMake control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents newsByMake As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''newsRepeater control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents newsRepeater As Global.System.Web.UI.WebControls.Repeater

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As crmWebClient.ABI
    Get
      Return CType(MyBase.Master, crmWebClient.ABI)
    End Get
  End Property
End Class
