'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8933
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class abiWanteds

  '''<summary>
  '''aside_right control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents aside_right As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''moduleTitleHeader control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents moduleTitleHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''typesOfWantedList control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents typesOfWantedList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''companyInformation control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents companyInformation As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''component control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents component As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''wanted_header control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents wanted_header As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''wantedListLiteral control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents wantedListLiteral As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''viewAllDiv control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents viewAllDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''Master property.
  '''</summary>
  '''<remarks>
  '''Auto-generated property.
  '''</remarks>
  Public Shadows ReadOnly Property Master() As crmWebClient.ABI
    Get
      Return CType(MyBase.Master, crmWebClient.ABI)
    End Get
  End Property
End Class
