'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Aircraft_Edit_Features_Tab

  '''<summary>
  '''aircraft_edit control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents aircraft_edit As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''title_change control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents title_change As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''subheaderText control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents subheaderText As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''message control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents message As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''datagrid_features control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents datagrid_features As Global.System.Web.UI.WebControls.DataGrid

  '''<summary>
  '''add_new control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents add_new As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''new_row control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents new_row As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''clikfeat_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents clikfeat_name As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''status control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents status As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''seq_no control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents seq_no As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''insert control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents insert As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''buttons control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents buttons As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''Panel1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''update_text control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents update_text As Global.System.Web.UI.WebControls.Label
End Class
