'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class companySearch

  '''<summary>
  '''search_pnl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_pnl As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''company_search_attention control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents company_search_attention As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''search_pnl_table control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_pnl_table As Global.System.Web.UI.WebControls.Table

  '''<summary>
  '''regular_search control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents regular_search As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''search_for_lbl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_for_lbl As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''search_for_txt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_for_txt As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''search_where control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_where As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''search_in control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_in As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''search_for_cbo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_for_cbo As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''search_button control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_button As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''adv_search control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents adv_search As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''TableRow1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableRow1 As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''Company_Phone control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Company_Phone As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''company_phone_number control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents company_phone_number As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''MergeList control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents MergeList As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''activity_view control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents activity_view As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''stat_lbl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents stat_lbl As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''status_cbo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents status_cbo As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''sub_lbl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents sub_lbl As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''subset control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents subset As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''show_all control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents show_all As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''location_search control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents location_search As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''country control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents country As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''state control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents state As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''types_of_owners control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents types_of_owners As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''city_label control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents city_label As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''city_textbox control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents city_textbox As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''fields control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents fields As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''special_field_cbo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents special_field_cbo As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''special_field_txt control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents special_field_txt As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''Button1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Button1 As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''Flyout1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Flyout1 As Global.OboutInc.Flyout2.Flyout

  '''<summary>
  '''special_field_view control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents special_field_view As Global.System.Web.UI.WebControls.CheckBox
End Class
