'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8793
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Contact_Reference_Edit_Template

  '''<summary>
  '''view_panel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents view_panel As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''view_panel_table control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents view_panel_table As Global.System.Web.UI.WebControls.Table

  '''<summary>
  '''sep1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents sep1 As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''TableRow1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableRow1 As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''Company_View control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Company_View As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''company_view_text control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents company_view_text As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ac_search control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ac_search As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''ac_sear control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ac_sear As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''ac_search_button control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ac_search_button As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TableRow2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableRow2 As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''TableCell1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell1 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''aircraft_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents aircraft_name As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''company_ac_add control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents company_ac_add As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''relationship control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents relationship As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ac_priority control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ac_priority As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ref_update control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ref_update As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''add_ref control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents add_ref As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''sep control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents sep As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''contact_ref_add control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contact_ref_add As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''aircraft_edit_text control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents aircraft_edit_text As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''contact_ref_add_errormsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contact_ref_add_errormsg As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''Table1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Table1 As Global.System.Web.UI.WebControls.Table

  '''<summary>
  '''TableRow3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableRow3 As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''TableCell2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell2 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''ac_info_display control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ac_info_display As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''ac_ref_instructions control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ac_ref_instructions As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''contact_ref_id control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contact_ref_id As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''jetnet_comp_id control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents jetnet_comp_id As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''client_comp_id control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents client_comp_id As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''existing_company_button control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents existing_company_button As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''search_company_button control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_company_button As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''TableCell5 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell5 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''contactQuickEntry control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contactQuickEntry As Global.System.Web.UI.HtmlControls.HtmlInputButton

  '''<summary>
  '''TableRow4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableRow4 As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''TableCell4 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell4 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''existing_company_panel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents existing_company_panel As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''existing_subset control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents existing_subset As Global.System.Web.UI.WebControls.RadioButtonList

  '''<summary>
  '''second_existing_company_panel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents second_existing_company_panel As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''Label1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''existing_first control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents existing_first As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''Label2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''existing_last control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents existing_last As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''contact_search_ref_2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contact_search_ref_2 As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''search_company_panel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents search_company_panel As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''input control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents input As Global.System.Web.UI.WebControls.RadioButtonList

  '''<summary>
  '''company control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents company As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''first_name_vis control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents first_name_vis As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''first control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents first As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''last_name_vis control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents last_name_vis As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''last control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents last As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''searching_cont_ref control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents searching_cont_ref As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''customize_reference control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents customize_reference As Global.System.Web.UI.WebControls.TableRow

  '''<summary>
  '''TableCell3 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TableCell3 As Global.System.Web.UI.WebControls.TableCell

  '''<summary>
  '''comp_name_vis control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents comp_name_vis As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''comp_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents comp_name As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''contact_name_vis control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contact_name_vis As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''contact_name control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contact_name As Global.System.Web.UI.WebControls.ListBox

  '''<summary>
  '''contact_info control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents contact_info As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''customize_relationship control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents customize_relationship As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''relationship_con control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents relationship_con As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''priority control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents priority As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''ref_two_add control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ref_two_add As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''add_cont_ref control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents add_cont_ref As Global.System.Web.UI.WebControls.ImageButton
End Class
