'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4971
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class JobsSearch

    '''<summary>
    '''search_pnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_pnl As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''search_pnl_table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_pnl_table As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''regular_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents regular_search As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''search_for_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_for_lbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''search_for_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_for_txt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''search_where control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_where As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''search_in control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_in As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''search_for_cbo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_for_cbo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''search_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_button As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''adv_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adv_search As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''activity_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents activity_view As Global.System.Web.UI.WebControls.TableRow

    '''<summary>
    '''status_cbo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_cbo As Global.System.Web.UI.WebControls.DropDownList
End Class
