'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class View_Mobile
    
    '''<summary>
    '''containerBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents containerBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''searchBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchBox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MobileSearchVisible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MobileSearchVisible As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''makeModelDynamic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents makeModelDynamic As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''description_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents description_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''mainImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainImage As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''description_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents description_text As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''market_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents market_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''market_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents market_text As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''fleet_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fleet_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fleet_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fleet_text As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''performance_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents performance_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''performance_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents performance_text As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''operating_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operating_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''operating_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operating_text As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''trends_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trends_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''FOR_SALE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FOR_SALE As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''AVG_PRICE_MONTH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AVG_PRICE_MONTH As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''AVG_DAYS_ON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AVG_DAYS_ON As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''PER_MONTH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PER_MONTH As Global.System.Web.UI.DataVisualization.Charting.Chart
    
    '''<summary>
    '''trends_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trends_text As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''forSale_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents forSale_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''forsale_text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents forsale_text As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''AircraftSearchDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AircraftSearchDataList As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''sold_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sold_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''retailText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents retailText As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''TransactionSearchDataList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionSearchDataList As Global.System.Web.UI.WebControls.DataList
    
    '''<summary>
    '''star_box control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents star_box As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''starHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents starHeader As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''starReportHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents starReportHolder As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''starText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents starText As Global.System.Web.UI.WebControls.Literal
End Class
